apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l4dv3d314-java-springboot
  janus-idp.io/tekton: l4dv3d314-java-springboot
  backstage.io/kubernetes-id: l4dv3d314-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l4dv3d314-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
